version: "3.8"
services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    depends_on:
      - mysql
    environment:
      WORDPRESS_DB_HOST: mysql
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: "March19th!"
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content/
    networks:
      caddnation:
        ipv4_address: "10.56.1.21"
  mysql:
    image: "mysql:latest"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: "March19th!"
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      caddnation:
        ipv4_address: "10.56.1.20"
networks:
  caddnation:
    ipam:
      driver: default
      config:
      - subnet: "10.56.1.0/24"
